from PyQt5.QtWidgets import QWidget, QGridLayout, QSpacerItem, QSizePolicy
from qmaterialwidgets import ComboBox, TextEdit, TitleLabel, TonalPushButton


class FrpcLogPage(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)

        self.setContentsMargins(8, 8, 8, 8)
        self.setObjectName("FrpcLogPage")
        self.gridLayout = QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QSpacerItem(20, 10, QSizePolicy.Minimum, QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 4)
        self.frpcLogTextEdit = TextEdit(self)
        self.frpcLogTextEdit.setUndoRedoEnabled(False)
        self.frpcLogTextEdit.setReadOnly(True)
        self.frpcLogTextEdit.setObjectName("frpcLogTextEdit")
        self.gridLayout.addWidget(self.frpcLogTextEdit, 3, 0, 1, 4)
        self.TitleLabel = TitleLabel(self)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleLabel.sizePolicy().hasHeightForWidth())
        self.TitleLabel.setSizePolicy(sizePolicy)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 0, 0, 1, 1)
        self.clearLogBtn = TonalPushButton(self)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearLogBtn.sizePolicy().hasHeightForWidth())
        self.clearLogBtn.setSizePolicy(sizePolicy)
        self.clearLogBtn.setObjectName("clearLogBtn")
        self.gridLayout.addWidget(self.clearLogBtn, 2, 0, 1, 1)
        self.saveLogBtn = TonalPushButton(self)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveLogBtn.sizePolicy().hasHeightForWidth())
        self.saveLogBtn.setSizePolicy(sizePolicy)
        self.saveLogBtn.setObjectName("saveLogBtn")
        self.gridLayout.addWidget(self.saveLogBtn, 2, 1, 1, 1)
        self.frpcLogFilterComboBox = ComboBox(self)
        self.frpcLogFilterComboBox.setObjectName("frpcLogFilterComboBox")
        self.gridLayout.addWidget(self.frpcLogFilterComboBox, 2, 2, 1, 2)
        self.TitleLabel.setText("日志")
        self.clearLogBtn.setText("清空")
        self.saveLogBtn.setText("保存日志")
