from PyQt5.QtWidgets import QWidget, QVBoxLayout, QSpacerItem, QSizePolicy, QFrame, QGridLayout
from PyQt5.QtCore import Qt, QRect
from .Multiplex.ScollArea import NormalSmoothScrollArea

from qmaterialwidgets import (
    BodyLabel,
    OutlinedCardWidget,
    SubtitleLabel,
    TitleLabel,
)


class HomePage(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("HomePage")

        self.gridLayout = QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.TitleLabel = TitleLabel(self)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleLabel.sizePolicy().hasHeightForWidth())
        self.TitleLabel.setSizePolicy(sizePolicy)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 0, 0, 1, 1)
        self.announcementWidget = OutlinedCardWidget(self)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.announcementWidget.sizePolicy().hasHeightForWidth())
        self.announcementWidget.setSizePolicy(sizePolicy)
        self.announcementWidget.setObjectName("announcementWidget")
        self.verticalLayout = QVBoxLayout(self.announcementWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.announcementTitle = SubtitleLabel(self.announcementWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.announcementTitle.sizePolicy().hasHeightForWidth())
        self.announcementTitle.setSizePolicy(sizePolicy)
        self.announcementTitle.setObjectName("announcementTitle")
        self.verticalLayout.addWidget(self.announcementTitle)
        self.announcementContent = BodyLabel(self.announcementWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.announcementContent.sizePolicy().hasHeightForWidth())
        self.announcementContent.setSizePolicy(sizePolicy)
        self.announcementContent.setObjectName("announcementContent")
        self.verticalLayout.addWidget(self.announcementContent)
        self.gridLayout.addWidget(self.announcementWidget, 2, 1, 1, 1)
        self.userInfoWidget = OutlinedCardWidget(self)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userInfoWidget.sizePolicy().hasHeightForWidth())
        self.userInfoWidget.setSizePolicy(sizePolicy)
        self.userInfoWidget.setObjectName("userInfoWidget")
        self.userInfoLayout = QVBoxLayout(self.userInfoWidget)
        self.userInfoLayout.setObjectName("verticalLayout_2")
        self.userInfoTitle = SubtitleLabel(self.userInfoWidget)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userInfoTitle.sizePolicy().hasHeightForWidth())
        self.userInfoTitle.setSizePolicy(sizePolicy)
        self.userInfoTitle.setObjectName("userInfoTitle")
        self.userInfoLayout.addWidget(self.userInfoTitle)
        self.userInfoScrollArea = NormalSmoothScrollArea(self.userInfoWidget)
        self.userInfoScrollArea.setFrameShape(QFrame.NoFrame)
        self.userInfoScrollArea.setFrameShadow(QFrame.Plain)
        self.userInfoScrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.userInfoScrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.userInfoScrollArea.setWidgetResizable(True)
        self.userInfoScrollArea.setAlignment(Qt.AlignCenter)
        self.userInfoScrollArea.setObjectName("userInfoScrollArea")
        self.userInfoSC = QWidget()
        self.userInfoSC.setGeometry(QRect(0, 0, 318, 330))
        self.userInfoSC.setObjectName("userInfoSC")
        self.userInfoScrollArea.setWidget(self.userInfoSC)
        self.userInfoLayout.addWidget(self.userInfoScrollArea)
        self.gridLayout.addWidget(self.userInfoWidget, 2, 0, 1, 1)
        spacerItem = QSpacerItem(20, 10, QSizePolicy.Minimum, QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 2)

        self.TitleLabel.setText(" 主页")
        self.announcementTitle.setText(" 公告")
        self.announcementContent.setText("")
        self.userInfoTitle.setText(" 用户信息")
